In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
import xlrd

Preprocess step:
1. Read data
   1. as
2.

# Read Data

In [2]:
df = pd.read_table("data/provinsi_sumsel (1).txt", delimiter=";",
                  names=['code', 'machine', 'provinsi', 'kabupaten', 'kecamatan', 'location', 'date', 'rain', 'soil', 'gwl', 'temp'],
                  header=None)
df

c:\users\akimp\appdata\local\programs\python\python39\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (6,7,8,9,10) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,code,machine,provinsi,kabupaten,kecamatan,location,date,rain,soil,gwl,temp
0,BRG_160205_01,286823772,SUMATERA SELATAN,OGAN KOMERING ILIR,KOTA KAYU AGUNG,Kedaton (Demplot),181109180000,0.0,88.2,0.148,28.3
1,BRG_160205_01,286823772,SUMATERA SELATAN,OGAN KOMERING ILIR,KOTA KAYU AGUNG,Kedaton (Demplot),181109181000,0.2,87.8,0.156,28.6
2,BRG_160205_01,286823772,SUMATERA SELATAN,OGAN KOMERING ILIR,KOTA KAYU AGUNG,Kedaton (Demplot),181109182000,0.0,87.4,0.166,28.6
3,BRG_160205_01,286823772,SUMATERA SELATAN,OGAN KOMERING ILIR,KOTA KAYU AGUNG,Kedaton (Demplot),181109183000,0.0,87.4,0.166,28.9
4,BRG_160205_01,286823772,SUMATERA SELATAN,OGAN KOMERING ILIR,KOTA KAYU AGUNG,Kedaton (Demplot),181109184000,0.0,87.0,0.175,28.9
...,...,...,...,...,...,...,...,...,...,...,...
660993,BRG_160611_01,286827114,SUMATERA SELATAN,MUSI BANYUASIN,LALAN,Karang agung,200110031000,0.0,28.8,1.733,29.5
660994,BRG_160611_01,286827114,SUMATERA SELATAN,MUSI BANYUASIN,LALAN,Karang agung,200110032000,0.0,28.7,1.736,28.9
660995,BRG_160611_01,286827114,SUMATERA SELATAN,MUSI BANYUASIN,LALAN,Karang agung,200110033000,0.0,29.0,1.733,30.1
660996,BRG_160611_01,286827114,SUMATERA SELATAN,MUSI BANYUASIN,LALAN,Karang agung,200110033000,0.0,29.0,1.731,29.8
660997,BRG_160611_01,286827114,SUMATERA SELATAN,MUSI BANYUASIN,LALAN,Karang agung,200110034000,0.0,29.0,1.733,30.1

In [3]:
df.dtypes

code         object
machine       int64
provinsi     object
kabupaten    object
kecamatan    object
location     object
date         object
rain         object
soil         object
gwl          object
temp         object
dtype: object

# Change data type

In [4]:
df['rain'] = pd.to_numeric(df['rain'], errors='coerce')
df['soil'] = pd.to_numeric(df['soil'], errors='coerce')
df['gwl'] = pd.to_numeric(df['gwl'], errors='coerce')
df['temp'] = pd.to_numeric(df['temp'], errors='coerce')

In [5]:
df.dtypes

code          object
machine        int64
provinsi      object
kabupaten     object
kecamatan     object
location      object
date          object
rain         float64
soil         float64
gwl          float64
temp         float64
dtype: object

In [6]:
df.isnull().sum()

code          0
machine       0
provinsi      0
kabupaten     0
kecamatan     0
location      0
date          0
rain         45
soil          2
gwl           2
temp          7
dtype: int64

In [7]:
df[df['soil'].isnull()]

,code,machine,provinsi,kabupaten,kecamatan,location,date,rain,soil,gwl,temp
385087,BRG_160224_01,286823786,SUMATERA SELATAN,OGAN KOMERING ILIR,PEDAMARAN,Cinta Jaya 1,Lat,NaN,NaN,NaN,NaN
429289,BRG_160224_02,286823412,SUMATERA SELATAN,OGAN KOMERING ILIR,PEDAMARAN,Cinta Jaya 2,D,NaN,NaN,NaN,NaN

In [8]:
df[df['gwl'].isnull()]

,code,machine,provinsi,kabupaten,kecamatan,location,date,rain,soil,gwl,temp
385087,BRG_160224_01,286823786,SUMATERA SELATAN,OGAN KOMERING ILIR,PEDAMARAN,Cinta Jaya 1,Lat,NaN,NaN,NaN,NaN
429289,BRG_160224_02,286823412,SUMATERA SELATAN,OGAN KOMERING ILIR,PEDAMARAN,Cinta Jaya 2,D,NaN,NaN,NaN,NaN

In [9]:
df[df['temp'].isnull()]

,code,machine,provinsi,kabupaten,kecamatan,location,date,rain,soil,gwl,temp
202658,BRG_160214_02,286827117,SUMATERA SELATAN,OGAN KOMERING ILIR,AIR SUGIHAN,Padang Sugihan 2 (SM),191229042000,0.0,0.0,2.136,NaN
244915,BRG_160214_03,286827062,SUMATERA SELATAN,OGAN KOMERING ILIR,AIR SUGIHAN,Padang Sugihan 3 (SM),191020105000,0.0,0.0,0.952,NaN
251913,BRG_160214_03,286827062,SUMATERA SELATAN,OGAN KOMERING ILIR,AIR SUGIHAN,Padang Sugihan 3 (SM),191205023000,0.0,0.0,1.533,NaN
385087,BRG_160224_01,286823786,SUMATERA SELATAN,OGAN KOMERING ILIR,PEDAMARAN,Cinta Jaya 1,Lat,NaN,NaN,NaN,NaN
421258,BRG_160224_02,286823412,SUMATERA SELATAN,OGAN KOMERING ILIR,PEDAMARAN,Cinta Jaya 2,190427092000,0.0,0.0,1.665,NaN
429289,BRG_160224_02,286823412,SUMATERA SELATAN,OGAN KOMERING ILIR,PEDAMARAN,Cinta Jaya 2,D,NaN,NaN,NaN,NaN
503581,BRG_160609_01,286823560,SUMATERA SELATAN,MUSI BANYUASIN,BAYUNG LENCIR,Muara Medak 1,190503135000,0.0,0.0,1.843,NaN

In [10]:
df[df['rain'].isnull()]

,code,machine,provinsi,kabupaten,kecamatan,location,date,rain,soil,gwl,temp
900,BRG_160205_01,286823772,SUMATERA SELATAN,OGAN KOMERING ILIR,KOTA KAYU AGUNG,Kedaton (Demplot),181115210000,NaN,81.0,2.007,31.1
53343,BRG_160205_02,286823691,SUMATERA SELATAN,OGAN KOMERING ILIR,PEDAMARAN,Kedaton,190101204000,NaN,95.0,2.034,29.5
66704,BRG_160205_02,286823691,SUMATERA SELATAN,OGAN KOMERING ILIR,PEDAMARAN,Kedaton,190323165000,NaN,93.7,3.172,31.4
70732,BRG_160205_02,286823691,SUMATERA SELATAN,OGAN KOMERING ILIR,PEDAMARAN,Kedaton,190411145000,NaN,93.4,2.930,31.7
155050,BRG_160214_02,286827117,SUMATERA SELATAN,OGAN KOMERING ILIR,AIR SUGIHAN,Padang Sugihan 2 (SM),181112235000,NaN,76.2,1.013,29.2
156003,BRG_160214_02,286827117,SUMATERA SELATAN,OGAN KOMERING ILIR,AIR SUGIHAN,Padang Sugihan 2 (SM),181119115000,NaN,76.4,1.594,28.3
162378,BRG_160214_02,286827117,SUMATERA SELATAN,OGAN KOMERING ILIR,AIR SUGIHAN,Padang Sugihan 2 (SM),190101224000,NaN,75.7,2.178,29.5
169894,BRG_160214_02,286827117,SUMATERA SELATAN,OGAN KOMERING ILIR,AIR SUGIHAN,Padang Sugihan 2 (SM),190318184000,NaN,58.4,2.422,30.7
205546,BRG_160214_03,286827062,SUMATERA SELATAN,OGAN KOMERING ILIR,AIR SUGIHAN,Padang Sugihan 3 (SM),181110142000,NaN,7.5,1.316,34.9
209396,BRG_160214_03,286827062,SUMATERA SELATAN,OGAN KOMERING ILIR,AIR SUGIHAN,Padang Sugihan 3 (SM),181206151000,NaN,62.7,2.019,31.1
215018,BRG_160214_03,286827062,SUMATERA SELATAN,OGAN KOMERING ILIR,AIR SUGIHAN,Padang Sugihan 3 (SM),190129205000,NaN,58.5,1.960,30.1
215133,BRG_160214_03,286827062,SUMATERA SELATAN,OGAN KOMERING ILIR,AIR SUGIHAN,Padang Sugihan 3 (SM),190130164000,NaN,58.9,1.975,30.4
216009,BRG_160214_03,286827062,SUMATERA SELATAN,OGAN KOMERING ILIR,AIR SUGIHAN,Padang Sugihan 3 (SM),190205153000,NaN,58.8,2.354,29.8
216011,BRG_160214_03,286827062,SUMATERA SELATAN,OGAN KOMERING ILIR,AIR SUGIHAN,Padang Sugihan 3 (SM),190205154000,NaN,58.8,2.388,29.8
217410,BRG_160214_03,286827062,SUMATERA SELATAN,OGAN KOMERING ILIR,AIR SUGIHAN,Padang Sugihan 3 (SM),190216140000,NaN,57.9,2.415,30.1
219081,BRG_160214_03,286827062,SUMATERA SELATAN,OGAN KOMERING ILIR,AIR SUGIHAN,Padang Sugihan 3 (SM),190228130000,NaN,57.4,2.459,30.4
226409,BRG_160214_03,286827062,SUMATERA SELATAN,OGAN KOMERING ILIR,AIR SUGIHAN,Padang Sugihan 3 (SM),190622071000,NaN,61.6,2.080,29.5
265045,BRG_160219_02,286827008,SUMATERA SELATAN,OGAN KOMERING ILIR,PANGKALAN LAPAM,Air Rumbai,190204041000,NaN,69.2,2.283,28.0
314063,BRG_160224_01,286823786,SUMATERA SELATAN,OGAN KOMERING ILIR,PEDAMARAN,Cinta Jaya 1,190207232000,NaN,90.8,2.190,28.6
321516,BRG_160224_01,286823786,SUMATERA SELATAN,OGAN KOMERING ILIR,PEDAMARAN,Cinta Jaya 1,190329085000,NaN,10.8,1.897,29.5
321520,BRG_160224_01,286823786,SUMATERA SELATAN,OGAN KOMERING ILIR,PEDAMARAN,Cinta Jaya 1,190329092000,NaN,10.7,1.892,29.8
385087,BRG_160224_01,286823786,SUMATERA SELATAN,OGAN KOMERING ILIR,PEDAMARAN,Cinta Jaya 1,Lat,NaN,NaN,NaN,NaN
396436,BRG_160224_02,286823412,SUMATERA SELATAN,OGAN KOMERING ILIR,PEDAMARAN,Cinta Jaya 2,181214191000,NaN,86.7,2.148,30.1
400550,BRG_160224_02,286823412,SUMATERA SELATAN,OGAN KOMERING ILIR,PEDAMARAN,Cinta Jaya 2,190107150000,NaN,83.4,2.004,30.1
417617,BRG_160224_02,286823412,SUMATERA SELATAN,OGAN KOMERING ILIR,PEDAMARAN,Cinta Jaya 2,190411151000,NaN,86.3,1.958,30.1
425679,BRG_160224_02,286823412,SUMATERA SELATAN,OGAN KOMERING ILIR,PEDAMARAN,Cinta Jaya 2,190516080000,NaN,30.8,1.579,31.1
426479,BRG_160224_02,286823412,SUMATERA SELATAN,OGAN KOMERING ILIR,PEDAMARAN,Cinta Jaya 2,190520034000,NaN,25.9,1.636,30.1
429289,BRG_160224_02,286823412,SUMATERA SELATAN,OGAN KOMERING ILIR,PEDAMARAN,Cinta Jaya 2,D,NaN,NaN,NaN,NaN
430472,BRG_160224_02,286823412,SUMATERA SELATAN,OGAN KOMERING ILIR,PEDAMARAN,Cinta Jaya 2,190608074000,NaN,36.7,1.387,30.4
430482,BRG_160224_02,286823412,SUMATERA SELATAN,OGAN KOMERING ILIR,PEDAMARAN,Cinta Jaya 2,190608074000,NaN,36.7,1.387,30.4
455763,BRG_160224_02,286823412,SUMATERA SELATAN,OGAN KOMERING ILIR,PEDAMARAN,Cinta Jaya 2,191201065000,NaN,28.4,1.120,32.4
459812,BRG_160224_03,286823525,SUMATERA SELATAN,OGAN KOMERING ILIR,PEDAMARAN,Cinta Jaya 3,181110193000,NaN,3.9,0.004,31.7
461835,BRG_160224_03,286823525,SUMATERA SELATAN,OGAN KOMERING ILIR,PEDAMARAN,Cinta Jaya 3,181124175000,NaN,3.8,0.004,31.4
495506,BRG_160609_01,286823560,SUMATERA SELATAN,MUSI BANYUASIN,BAYUNG LENCIR,Muara Medak 1,190101182000,NaN,88.1,1.768,31.1
498386,BRG_160609_01,286823560,SUMATERA SELATAN,MUSI BANYUASIN,BAYUNG LENCIR,Muara Medak 1,190331041000,NaN,84.5,1.785,27.5
502414,BRG_160609_01,286823560,SUMATERA SELATAN,MUSI BANYUASIN,BAYUNG LENCIR,Muara Medak 1,190426154000,NaN,83.4,1.873,30.1
505685,BRG_160609_01,286823560,SUMATERA SELATAN,MUSI BANYUASIN,BAYUNG LENCIR,Muara Medak 1,190516082000,NaN,84.6,1.660,30.7
554890,BRG_160609_02,286823683,SUMATERA SELATAN,MUSI BANYUASIN,BAYUNG LENCIR,Muara Medak 2,190503084000,NaN,44.1,2.239,30.4
571078,BRG_160611_01,286827114,SUMATERA SELATAN,MUSI BANYUASIN,LALAN,Karang agung,181205125000,NaN,71.7,2.178,30.4
581429,BRG_160611_01,286827114,SUMATERA SELATAN,MUSI BANYUASIN,LALAN,Karang agung,190210043000,NaN,55.8,2.085,28.9
588383,BRG_160611_01,286827114,SUMATERA SELATAN,MUSI BANYUASIN,LALAN,Karang agung,190318165000,NaN,45.3,1.860,32.1
589661,BRG_160611_01,286827114,SUMATERA SELATAN,MUSI BANYUASIN,LALAN,Karang agung,190325151000,NaN,21.0,2.056,32.4
601207,BRG_160611_01,286827114,SUMATERA SELATAN,MUSI BANYUASIN,LALAN,Karang agung,190512064000,NaN,56.8,1.848,30.4
609053,BRG_160611_01,286827114,SUMATERA SELATAN,MUSI BANYUASIN,LALAN,Karang agung,190612083000,NaN,57.7,1.829,28.6
627761,BRG_160611_01,286827114,SUMATERA SELATAN,MUSI BANYUASIN,LALAN,Karang agung,190827131000,NaN,49.1,1.296,26.7

## Remove inconsistent reading

In [11]:
df.iloc[385087]

code              BRG_160224_01
machine               286823786
provinsi       SUMATERA SELATAN
kabupaten    OGAN KOMERING ILIR
kecamatan             PEDAMARAN
location           Cinta Jaya 1
date                        Lat
rain                        NaN
soil                        NaN
gwl                         NaN
temp                        NaN
Name: 385087, dtype: object

In [12]:
df.iloc[429289]

code              BRG_160224_02
machine               286823412
provinsi       SUMATERA SELATAN
kabupaten    OGAN KOMERING ILIR
kecamatan             PEDAMARAN
location           Cinta Jaya 2
date                          D
rain                        NaN
soil                        NaN
gwl                         NaN
temp                        NaN
Name: 429289, dtype: object

In [13]:
df = df.drop([385087, 429289])

In [17]:
df = df.reset_index(drop=True)

## Convert date

In [20]:
df['date'] = pd.to_datetime(df['date'], format='%y%m%d%H%M%S')
df

,code,machine,provinsi,kabupaten,kecamatan,location,date,rain,soil,gwl,temp
0,BRG_160205_01,286823772,SUMATERA SELATAN,OGAN KOMERING ILIR,KOTA KAYU AGUNG,Kedaton (Demplot),2018-11-09 18:00:00,0.0,88.2,0.148,28.3
1,BRG_160205_01,286823772,SUMATERA SELATAN,OGAN KOMERING ILIR,KOTA KAYU AGUNG,Kedaton (Demplot),2018-11-09 18:10:00,0.2,87.8,0.156,28.6
2,BRG_160205_01,286823772,SUMATERA SELATAN,OGAN KOMERING ILIR,KOTA KAYU AGUNG,Kedaton (Demplot),2018-11-09 18:20:00,0.0,87.4,0.166,28.6
3,BRG_160205_01,286823772,SUMATERA SELATAN,OGAN KOMERING ILIR,KOTA KAYU AGUNG,Kedaton (Demplot),2018-11-09 18:30:00,0.0,87.4,0.166,28.9
4,BRG_160205_01,286823772,SUMATERA SELATAN,OGAN KOMERING ILIR,KOTA KAYU AGUNG,Kedaton (Demplot),2018-11-09 18:40:00,0.0,87.0,0.175,28.9
...,...,...,...,...,...,...,...,...,...,...,...
660991,BRG_160611_01,286827114,SUMATERA SELATAN,MUSI BANYUASIN,LALAN,Karang agung,2020-01-10 03:10:00,0.0,28.8,1.733,29.5
660992,BRG_160611_01,286827114,SUMATERA SELATAN,MUSI BANYUASIN,LALAN,Karang agung,2020-01-10 03:20:00,0.0,28.7,1.736,28.9
660993,BRG_160611_01,286827114,SUMATERA SELATAN,MUSI BANYUASIN,LALAN,Karang agung,2020-01-10 03:30:00,0.0,29.0,1.733,30.1
660994,BRG_160611_01,286827114,SUMATERA SELATAN,MUSI BANYUASIN,LALAN,Karang agung,2020-01-10 03:30:00,0.0,29.0,1.731,29.8
660995,BRG_160611_01,286827114,SUMATERA SELATAN,MUSI BANYUASIN,LALAN,Karang agung,2020-01-10 03:40:00,0.0,29.0,1.733,30.1

In [21]:
df.dtypes

code                 object
machine               int64
provinsi             object
kabupaten            object
kecamatan            object
location             object
date         datetime64[ns]
rain                float64
soil                float64
gwl                 float64
temp                float64
dtype: object

# Remove duplicates

Duplicate data with same datetime with same code and machine will be removed

In [24]:
df['location'].unique()

array(['Kedaton (Demplot)', 'Kedaton', 'Padang Sugihan 1 (SM)',
       'Padang Sugihan 2 (SM)', 'Padang Sugihan 3 (SM)', 'Air Rumbai',
       'Cinta Jaya 1', 'Cinta Jaya 2', 'Cinta Jaya 3', 'Muara Medak 1',
       'Muara Medak 2', 'Karang agung'], dtype=object)

In [25]:
df['date'].unique()

array(['2018-11-09T18:00:00.000000000', '2018-11-09T18:10:00.000000000',
       '2018-11-09T18:20:00.000000000', ...,
       '2018-11-09T15:00:00.000000000', '2018-11-09T15:10:00.000000000',
       '2018-11-09T15:20:00.000000000'], dtype='datetime64[ns]')

In [ ]:
karang_agung     = df[df["stasiun"] == "Karang agung"]
# air_rumbai       = df[df["stasiun"] == ""]
# kedaton          = df[df["stasiun"] == ""]
# kedaton_demplot  = df[df["stasiun"] == ""]
# padang_sugihan_1 = df[df["stasiun"] == ""]
# padang_sugihan_2 = df[df["stasiun"] == ""]
# padang_sugihan_3 = df[df["stasiun"] == ""]
# cinta_jaya_1     = df[df["stasiun"] == ""]
# cinta_jaya_2     = df[df["stasiun"] == ""]
# cinta_jaya_3     = df[df["stasiun"] == ""]
# muara_medak_1    = df[df["stasiun"] == ""]
# muara_medak_2    = df[df["stasiun"] == ""]